### ISSUE TITLE
В главе 4.5 правка кода в разделе Выборка

### ISSUE THREAD

**Issue by sam0var** [DiscoverMeteor/DiscoverMeteor_Ru#119]
Публикации и подписки - Выборка

В блоке с кодом не хватает фигурных скобок для передачи объекта в функцию find. Если копировать, как есть, Meteor падает в crash.

Было:
> return Posts.find(author: 'bob-smith', category: 'JavaScript');

Надо:
> return Posts.find({author: 'bob-smith', category: 'JavaScript'});

В дополнение мне не понятно почему параметр авторства в тексте описан Bob Smith, а в параметре author bob-smith. У себя в приложении я использую готовый для публикации формат, т.е. как в книге описан по тексту. Мне не понятно использование описания в виде bob-smith, ну разве что для передачи class параметра, но зачем!?

**Comment by Slava** [comment]
fixed, thanks

на счет "bob-smith" - так это индетификатор в базе данных, а "Bob Smith" - имя человека, для которого создается документ.
