### ISSUE TITLE
В главе "Коллекции" папка collections находится в корне проекта, но в дальнейшем, в папке lib

### ISSUE THREAD

**Issue by jumasheff** [DiscoverMeteor/DiscoverMeteor_Ru#99]
Немного не явный переход файла posts.js с 'collections/posts.js' в 'lib/collections/posts.js'. Последнее можно найти на странице http://ru.discovermeteor.com/chapters/creating-posts/

**Comment by Slava** [comment]
перепроверил с английским оригиналом, они так описывают, сильно отличаться от оригинала не хочется.
